###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-member
  #  application:
  #    name: app-mayikt-weixin
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop-parent?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

####打印MyBatias日志
logging:
  level:
    ##开发环境使用DEBUG 生产环境使用INFO或者ERROR  DEBUG会打印较为详细的日志，而INFO仅打印核心 ERROR则打印错误信息
    com.t248.member.mapper: DEBUG

